name: self-evolve
on:
  workflow_dispatch:
  schedule:
    - cron: "13 4 * * *"
jobs:
  call:
    uses: rickballard/CoCache/.github/workflows/bpoe-self-evolve.yml@ae447f5a3f542798bd1ac3ba5c6112d7521550b5
